/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/editor/[id]': RouteRecordInfo<'/admin/editor/[id]', '/admin/editor/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/editor/new': RouteRecordInfo<'/admin/editor/new', '/admin/editor/new', Record<never, never>, Record<never, never>>,
    '/admin/editor/preview': RouteRecordInfo<'/admin/editor/preview', '/admin/editor/preview', Record<never, never>, Record<never, never>>,
    '/admin/firstsetup': RouteRecordInfo<'/admin/firstsetup', '/admin/firstsetup', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/logs': RouteRecordInfo<'/admin/logs', '/admin/logs', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
  }
}
